---
collections:
  - name: community.general
  - name: ansible.controller
  - name: community.crypto
  - name: ansible.posix
  - name: community.libvirt
  - name: ibm.ibm_zos_core
  - name: ibm.ibm_zosmf 
  - name: ibm.ibm_zos_sysauto 
  - name: ibm.ibm_zos_cics 
  - name: ibm.ibm_zos_ims 
  - name: ibm.zos_zoau_operator 
  - name: ibm.zos_nodejs_operator 
  - name: ibm.zos_python_operator 
  - name: ibm.zos_java_operator 
  - name: ibm.zos_opencpp_operator 
  - name: ibm.zos_go_operator
  - name: ibm.zos_package_manager
  - name: ibm.zos_ims_operator 
  - name: ibm.ibm_zhmc
  - name: ibm.operator_collection_sdk 
  - name: ibm.zos_cics_operator